### ISSUE TITLE
Travel scholarships not linked on main page

### ISSUE THREAD

**Issue by lcolladotor** [Bioconductor/BioC2020#61]
Hi,

I can't seem to find at the link to the travel scholarship details that I can see that the information exists here https://github.com/Bioconductor/BioC2020/blob/master/docs/scholarships.md. Is the information in this document correct? (from the dates it seems to be)

A CSDB member just asked me about this. 

Best,
Leo

**Comment by lpantano** [comment]
Yes, and this is the link in the web-page:
http://bioc2020.bioconductor.org/scholarships.html

Is this what you are looking for?



From: Leonardo Collado-Torres <notifications@github.com>
<notifications@github.com>
Reply: Bioconductor/BioC2020
<reply@reply.github.com>
<reply@reply.github.com>
Date: February 26, 2020 at 2:22:53 PM
To: Bioconductor/BioC2020 <bioc2020@noreply.github.com>
<bioc2020@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
<subscribed@noreply.github.com>
Subject:  [Bioconductor/BioC2020] Travel scholarships not linked on main
page (#61)

Hi,

I can't seem to find at the link to the travel scholarship details that I
can see exist here
https://github.com/Bioconductor/BioC2020/blob/master/docs/scholarships.md.
Is the information in this document correct? (from the dates it seems to be)

A CSDB member just asked me about this.

Best,
Leo

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Bioconductor/BioC2020/issues/61?email_source=notifications&email_token=AAML6HB3X5UXE3M2ROPXAXDRE26QZA5CNFSM4K4MI5N2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4IQR624Q>,
or unsubscribe

**Comment by mtmorgan** [comment]
It's discoverable under Call for submissions -> BioC2020: Travel awards. Does the query mean that this needs to be made more 'visible'? Maybe links at the top of the call-for-abstracts page could have a bulleted list of each 'call'?

**Comment by mdozmorov** [comment]
The page https://bioc2020.bioconductor.org/scholarships.html is indeed incomplete - it shows the orphaned link "To apply for a scholarship, complete the [Poster / Talk Submission Form][]." There is another link to the travel award at the bottom of the page. 

Unsure about terminology - are the scholarship and travel awards different?

**Comment by lpantano** [comment]
I changed to awards because the form tittle says awards.

**Comment by lcolladotor** [comment]
Hi,

I think that the confusion this CDSB member had and the same one I had is that https://bioc2020.bioconductor.org/travel-accommodations at the bottom includes the link to the google submission form for the travel awards instead of http://bioc2020.bioconductor.org/scholarships.html.

Thanks to your replies I can see now from https://github.com/Bioconductor/BioC2020/search?q=scholarships&unscoped_q=scholarships that the main landing page https://bioc2020.bioconductor.org/ does link to https://bioc2020.bioconductor.org/call-for-abstracts.html which then links to https://bioc2020.bioconductor.org/scholarships.html. Since I had found the link for the submission form at https://bioc2020.bioconductor.org/travel-accommodations (and that's the link I had shared to CDSB members) I was confused as I mentioned in the previous paragraph.

Best,
Leo

**Comment by lpantano** [comment]
I will try to make it more obvious later today, thanks for reporting this.

**Comment by lpantano** [comment]
I will try to make it more obvious later today, thanks for reporting this.

**Comment by lpantano** [comment]
I will try to make it more obvious later today, thanks for reporting this.

**Comment by lpantano** [comment]
I will try to make it more obvious later today, thanks for reporting this.

**Comment by lcolladotor** [comment]
By the way, I found the dates at https://bioc2020.bioconductor.org/scholarships.html confusing since it says that:

```
* Thursday March 15, 2020: Abstract Submissions opens.
* Thursday May 17, 2020: Abstract Submission deadline.
```

but my understanding was from the submission form https://docs.google.com/forms/d/e/1FAIpQLSdr__Ox7kWpTV0lwjJ7skD617HcWFQmPrJqyMpVN27darvZQg/viewform is that you need to submit way earlier. The form says:

```
Please use this form to submit an application for a travel award to attend the Bioc2020 meeting.  Notifications will be sent by March 24.
```

It seems like the right set of dates is displayed at https://bioc2020.bioconductor.org/call-for-abstracts 

Can you clarify this? Thanks!

**Comment by lpantano** [comment]
yeah, that is a good question. It was moved forward, and it seems is ok. Maybe the Form has the dates of last year, of the date we first thought. I will try to raise this in the mailing list again. Thanks and sorry
