### ISSUE TITLE
HAK

### ISSUE THREAD

**Issue by gullahoo** [Bioconductor/BioC2020#68]
This is a submission of  a suggested topic, in the short talks category of the upcoming conference:

Creating a MiniCran repository for a very page.rank() style library method, such as described in the following blog on Revolutions Analytics site:  "https://en.wikipedia.org/wiki/PageRank"  ,  but this repo designed specifically for usage with the biometry/bipartitite package of the cran-R repo.

The code can be included on this posters site, at request.   Thanks

**Comment by csoneson** [comment]
👋 @gullahoo - are you still interested in running this as a hackathon session during BioC2020? If so, could you provide a bit more concrete information about how you would like to structure the session from a practical point of view, and what the expected outcome would be? The session could then be scheduled on Tue, July 28, 12-12:55pm EDT (note that you also need to be registered for the conference in order to access the platform and run the session). Thanks!

**Comment by gullahoo** [comment]
@csoneson -   Sorry, this project morphed (forked) to a python version of the proposed library, as RStudio Cloud was having bugs as recently as April 20 with project code mysteriously going AWOL.  (See issues #21, #35 on https://github.com/rstudio/rscloud/issues)
On such a late notice, I cannot have the R version up and ready to speak on (sorry Charlotte), but if the conference is interested in a low-level C version of a statistical/numerical package I am currently in possession of for potential deployment,  it is possible I can forward an abstract to have somebody else present.  (It has more to do with efficient register usage for numerical constants) 
I have already scheduled something else during this timeslot.

**Comment by gullahoo** [comment]
Sorry @csoneson, I updated this to mention Issue #13  (and possibly #16) on the above posted link, and raised another concern with the contributors on this issue.  Since this issue is not related to BioConductor, at least directly, I will save it for the RStudio site.
Thanks!

**Comment by csoneson** [comment]
After discussion offline, the decision was taken to not run this as a hackathon session at BioC2020.
